# Explore ways to get branch name, especially when running on a tag or specific SHA
name: CI

on:
  push:
  workflow_dispatch:

jobs:
  branch-names:
    name: "Get Branch and Tag names"
    runs-on: ubuntu-latest
    outputs:
      # All branches associated with the github ref, as an arrary. Use fromJSON(...) to parse.
      branches: ${{ steps.branch-names.outputs.branches }}
      # Tag, if any for the ref (applies when ref is a tag)
      tag: ${{ steps.tag.outputs.tag }}
      # Tag without a leading "v"
      tag_num: ${{ steps.tag.outputs.tag_num }}
      # Ref is a tag
      is_tag: ${{ steps.tag.outputs.is_tag }}
      # Ref is a semver tag
      is_semver: ${{ steps.tag.outputs.is_semver }}
      # Tags (if more than one), for the ref. Applies whether or not the ref is a tag.
      tags: ${{ steps.tag.outputs.tags }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: branch-names
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          echo "raw=$raw"
          branches=$(echo "$raw" | sed -E -e 's/^[ ]+//; s,origin/,,; s/^/"/; s/$/",/; 1s/^/[/; $s/,/]/;' | tr -d '\n')
          echo "branches='$branches'" >> $GITHUB_OUTPUT
          echo "Branches is '$branches'."
      - id: tag
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          semver_regex="^v?(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$"
          # "Set the tag name..."
          if [[ "$GITHUB_REF" == "refs/tags/"* ]]; then
            REF=$(printf "%q" "$GITHUB_REF")
            TAG="${REF/refs\/tags\//}"
            TAG_NUM="${REF/refs\/tags\/v/}"

            echo "tag=$(eval printf "%s" "$TAG")" >> "$GITHUB_OUTPUT"
            echo "tag_num=$(eval printf "%s" "$TAG_NUM")" >> "$GITHUB_OUTPUT"
            echo "is_tag=true" >> "$GITHUB_OUTPUT"
            if [[ $TAG =~ $semver_regex ]]; then
              echo "is_semver=true" >> "$GITHUB_OUTPUT"
            else
              echo "is_semver=false" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "is_tag=false" >> "$GITHUB_OUTPUT"
            echo "is_semver=false" >> "$GITHUB_OUTPUT"
          fi
          # Get all the tags associated with the ref
          TAGS=$(git tag --points-at ${GITHUB_REF} | sed -E -e 's/^[ ]+//;s/^/"/; s/$/",/; 1s/^/[/; $s/,/]/;' | tr -d '\n' )
          echo "tags='$TAGS'" >> "$GITHUB_OUTPUT"
  release:
    name: "CD - Release"
    runs-on: ubuntu-latest
    needs: branch-names
    steps:
    - name: "Display Branch and Tag names"
      run: |
        printf "Branches (raw): %s\n" '${{needs.branch-names.outputs.branches}}'
        printf "Branches: %s\n" '${{fromJson(needs.branch-names.outputs.branches)}}'
        echo "Tag: ${{needs.branch-names.outputs.tag}}"
        echo "Tag Num: ${{needs.branch-names.outputs.tag_num}}"
        echo "Is Tag: ${{needs.branch-names.outputs.is_tag}}"
        echo "Is Semver: ${{needs.branch-names.outputs.is_semver}}"
        printf "Tags (raw): %s\n" '${{needs.branch-names.outputs.tags}}'
        printf "Tags: %s\n" '${{fromJson(needs.branch-names.outputs.tags)}}'
        echo "github.ref_protected: ${{github.ref_protected}}"

  gate-on-tag:
    name: "CD - Gate on Tag"
    runs-on: ubuntu-latest
    needs: branch-names
    if: github.ref_protected == 'true' && needs.branch-names.outputs.is_semver == 'true'
    steps:
    - name: "Display Branch and Tag names"
      run: |
        printf "Branches (raw): %s\n" '${{needs.branch-names.outputs.branches}}'
        printf "Branches: %s\n" '${{fromJson(needs.branch-names.outputs.branches)}}'
        echo "Tag: ${{needs.branch-names.outputs.tag}}"
        echo "Tag Num: ${{needs.branch-names.outputs.tag_num}}"
        echo "Is Tag: ${{needs.branch-names.outputs.is_tag}}"
        echo "Is Semver: ${{needs.branch-names.outputs.is_semver}}"
        printf "Tags (raw): %s\n" '${{needs.branch-names.outputs.tags}}'
        printf "Tags: %s\n" '${{fromJson(needs.branch-names.outputs.tags)}}'
